# Generated by Django 5.2 on 2025-10-23 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_file', models.FileField(upload_to='resumes/')),
                ('role', models.CharField(choices=[('Data Analyst', 'Data Analyst'), ('Data Scientist', 'Data Scientist'), ('Web Developer', 'Web Developer')], max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('match_score', models.FloatField(default=0)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
